### ISSUE TITLE
Add option to save the name of the person who wrote the message before saying the message?

### ISSUE THREAD

**Issue by elvisior** [rossbreytberg/twitch-tts#3]
Hey, your app is awesome.  Thanks heaps for making it and sharing it. 
As per the subject above could you please add an option so the text to speech could prefix the message with "<username> wrote" or maybe even let that be customisable as well?

**Comment by rossbreytberg** [comment]
Thanks for the suggestion @elvisior, this feature is now available in the latest update to both the source code and on the Microsoft Store at https://www.microsoft.com/en-us/p/twitch-tts/9pbvkpwxlx4f

**Comment by rossbreytberg** [comment]
Thanks for the suggestion @elvisior, this feature is now available in the latest update to the source code and on the Microsoft Store at https://www.microsoft.com/en-us/p/twitch-tts/9pbvkpwxlx4f

It is on by default but can be toggled from settings under Message Context -> Pronounce Names

**Comment by elvisior** [comment]
Awesome, I just tried it out and it's great!

Thanks!!!!
